### ISSUE TITLE
segmentation fault when initializing AutoSeededX917RNG

### ISSUE THREAD

**Issue by 3togo** [weidai11/cryptopp#1038]
Segmentation fault occurred during the initialization of this line of code
`CryptoPP::AutoSeededX917RNG<CryptoPP::DES_EDE3> rng;`.

Any pointer?

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff823355419 in ?? () from C:\msys64\mingw64\bin\libcryptopp.dll
(gdb) bt
#0  0x00007ff823355419 in ?? () from C:\msys64\mingw64\bin\libcryptopp.dll
#1  0x00007ff823357669 in ?? () from C:\msys64\mingw64\bin\libcryptopp.dll
#2  0x00007ff8233cbcdf in ?? () from C:\msys64\mingw64\bin\libcryptopp.dll
#3  0x00007ff8232ebc53 in ?? () from C:\msys64\mingw64\bin\libcryptopp.dll
#4  0x00007ff8232ebe70 in ?? () from C:\msys64\mingw64\bin\libcryptopp.dll
#5  0x00007ff6336b132b in CryptoPP::HashTransformation::CalculateDigest (
    this=0xb6f71fe598,
    digest=0x1d88d69ec30 "\r▒\272\r▒\272\r▒\272\r▒\272\r▒\272\r▒\272\r▒\272\r𭺫\253\253\253\253\253\253\253\253\253\253\253\253", <incomplete sequence \253>,
    input=0x1d88d69ebe0 "▒h▒▒6▒J▒▒▒䱀\t~\374\256~ǥ}|\245▒H▒▒%sXS▒▒\253\253\253\253\253\253\253\253\253\253\253\253", <incomplete sequence \253>, length=32)
    at C:/msys64/mingw64/include/cryptopp/cryptlib.h:1189
#6  0x00007ff6336e0350 in CryptoPP::HKDF<CryptoPP::SHA256>::DeriveKey (
    this=0xb6f71fe728,
    derived=0x1d88d69eb90 "\r▒\272\r▒\272\r▒\272\r▒\272\r▒\272\r▒\272\r▒\272\r𭺫\253\253\253\253\253\253\253\253\253\253\253\253", <incomplete sequence \253>, derivedLen=32,
    secret=0x1d88d69ebe0 "▒h▒▒6▒J▒▒▒䱀\t~\374\256~ǥ}|\245▒H▒▒%sXS▒▒\253\253\253\253\253\253\253\253\253\253\253\253", <incomplete sequence \253>,
    secretLen=32,
    salt=0x7ff6338340c0 <CryptoPP::HKDF<CryptoPP::SHA256>::GetNullVector()::s_NullVector> "", saltLen=32, info=0xb6f71fe730 "X9.17 key generation",
    infoLen=20) at C:/msys64/mingw64/include/cryptopp/hkdf.h:147
#7  0x00007ff6336b0827 in CryptoPP::AutoSeededX917RNG<CryptoPP::DES_EDE3>::Reseed (this=0xb6f71fea70, blocking=false, input=0x0, length=0)
    at C:/msys64/mingw64/include/cryptopp/osrng.h:259
#8  0x00007ff6336b09a8 in CryptoPP::AutoSeededX917RNG<CryptoPP::DES_EDE3>::AutoSeededX917RNG (this=0xb6f71fea70, blocking=false, autoSeed=true)
    at C:/msys64/mingw64/include/cryptopp/osrng.h:206
#9  0x00007ff6334e02a1 in CClientCreditsList::CreateKeyPair (
    this=0x1d88d69ea50)
    at C:/msys64/home/eli/git/amule/src/ClientCreditsList.cpp:254
#10 0x00007ff6334e087e in CClientCreditsList::InitalizeCrypting (
    this=0x1d88d69ea50)
    at C:/msys64/home/eli/git/amule/src/ClientCreditsList.cpp:309
#11 0x00007ff6334dec16 in CClientCreditsList::CClientCreditsList (
    this=0x1d88d69ea50)
    at C:/msys64/home/eli/git/amule/src/ClientCreditsList.cpp:54
#12 0x00007ff6334c2fcf in CamuleApp::OnInit (this=0x1d88ad3b830)
    at C:/msys64/home/eli/git/amule/src/amule.cpp:513
#13 0x00007ff63355d898 in CamuleGuiApp::OnInit (this=0x1d88ad3b830)
    at C:/msys64/home/eli/git/amule/src/amule-gui.cpp:288
#14 0x00007ff6336988d2 in wxAppConsoleBase::CallOnInit (this=0x1d88ad3b830)
    at C:/msys64/mingw64/include/wx-3.0/wx/app.h:93
#15 0x000000006faff4a2 in wxbase30u_gcc_custom!_Z11wxEntryRealRiPPw ()
   from C:\msys64\mingw64\bin\wxbase30u_gcc_custom.dll
#16 0x000000006e74a051 in wxmsw30u_core_gcc_custom!_Z7wxEntryP11HINSTANCE__S0_Pci () from C:\msys64\mingw64\bin\wxmsw30u_core_gcc_custom.dll
#17 0x00007ff63355cce7 in WinMain (hInstance=0x7ff633450000,
    hPrevInstance=0x0, nCmdShow=10)
    at C:/msys64/home/eli/git/amule/src/amule-gui.cpp:95
#18 0x00007ff6337a1a12 in main (flags=<optimized out>,
    cmdline=<optimized out>, inst=<optimized out>)
    at C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18
#19 0x00007ff6334513c1 in __tmainCRTStartup ()
    at C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:321
#20 0x00007ff6334514d6 in WinMainCRTStartup ()
    at C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:176
(gdb)
```

**Comment by noloader** [comment]
> Any pointer?

Disable Link Time Optimizations. Also see [Link Time Optimization](https://www.cryptopp.com/wiki/Link_Time_Optimization) on the Crypto++ wiki. (I have no idea what problem LTO was intended to solve, but it does an awful job in practice. It transforms a working program into a non-working one).
