### ISSUE TITLE
SHA3 CalculateDigest() results in SIGSEGV

### ISSUE THREAD

**Issue by GeorgeMatveev** [weidai11/cryptopp#128]
Simple program that attempts to calculate message digest from string compiles without warnings,
but then crashes. gdb shows the following:

```
Program received signal SIGSEGV, Segmentation fault.
0x000000000049e6db in CryptoPP::SHA3::TruncatedFinal (this=0x7fffffffd7e0, 
    hash=0x7fffffffd960 "\270\f\257\367\377\177", size=256) at sha3.cpp:284
284		m_state.BytePtr()[r()-1] ^= 0x80;
(gdb) bt
#0  0x000000000049e6db in CryptoPP::SHA3::TruncatedFinal (this=0x7fffffffd7e0, 
    hash=0x7fffffffd960 "\270\f\257\367\377\177", size=256) at sha3.cpp:284
#1  0x000000000040423f in CryptoPP::HashTransformation::CalculateDigest (this=0x7fffffffd7e0, 
    digest=0x7fffffffd960 "\270\f\257\367\377\177", input=0x71a078 "Räksmörgås 12", length=16)
    at /usr/include/cryptopp/cryptlib.h:928
#2  0x0000000000403882 in sha3 (message=...) at sha3.cpp:30
#3  0x0000000000403bfa in main (argc=1, argv=0x7fffffffdbf8) at sha3.cpp:53
(gdb) up
#1  0x000000000040423f in CryptoPP::HashTransformation::CalculateDigest (this=0x7fffffffd7e0, 
    digest=0x7fffffffd960 "\270\f\257\367\377\177", input=0x71a078 "Räksmörgås 12", length=16)
    at /usr/include/cryptopp/cryptlib.h:928
928			{Update(input, length); Final(digest);}
(gdb)
```

Any ideas what is wrong?

**Comment by noloader** [comment]
@GeorgeMatveev,

Please perform the following:

```
git clone https://github.com/weidai11/cryptopp.git cryptopp-test
cd cryptopp-test
make cryptest.exe
./cryptest.exe v
./cryptest.exe tv all
```

Then report back.

If all the self tests pass, then the problem lies somewhere else.

**Comment by noloader** [comment]
Also see [Issue 126](http://github.com/weidai11/cryptopp/issues/126).
