### ISSUE TITLE
https://cryptopp.com/wiki/ fails to load

### ISSUE THREAD

**Issue by Talkless** [weidai11/cryptopp#911]
Looks like wiki is down. I get this:
```
Sorry! This site is experiencing technical difficulties.

Try waiting a few minutes and reloading.

(Cannot access the database)

Backtrace:

#0 /var/www/html/w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(769): Wikimedia\Rdbms\LoadBalancer->reportConnectionError()
#1 /var/www/html/w/includes/GlobalFunctions.php(2694): Wikimedia\Rdbms\LoadBalancer->getConnection(0, Array, false)
#2 /var/www/html/w/includes/cache/localisation/LCStoreDB.php(54): wfGetDB(-1)
#3 /var/www/html/w/includes/cache/localisation/LocalisationCache.php(410): LCStoreDB->get('en', 'deps')
#4 /var/www/html/w/includes/cache/localisation/LocalisationCache.php(456): LocalisationCache->isExpired('en')
#5 /var/www/html/w/includes/cache/localisation/LocalisationCache.php(375): LocalisationCache->initLanguage('en')
#6 /var/www/html/w/includes/cache/localisation/LocalisationCache.php(294): LocalisationCache->loadSubitem('en', 'messages', 'title-invalid-e...')
#7 /var/www/html/w/languages/Language.php(2655): LocalisationCache->getSubitem('en', 'messages', 'title-invalid-e...')
#8 /var/www/html/w/includes/cache/MessageCache.php(979): Language->getMessage('title-invalid-e...')
#9 /var/www/html/w/includes/cache/MessageCache.php(937): MessageCache->getMessageForLang(Object(LanguageEn), 'title-invalid-e...', false, Array)
#10 /var/www/html/w/includes/cache/MessageCache.php(879): MessageCache->getMessageFromFallbackChain(Object(LanguageEn), 'title-invalid-e...', false)
#11 /var/www/html/w/includes/Message.php(1299): MessageCache->get('title-invalid-e...', false, Object(LanguageEn))
#12 /var/www/html/w/includes/Message.php(851): Message->fetchMessage()
#13 /var/www/html/w/includes/Message.php(943): Message->toString('text')
#14 /var/www/html/w/includes/title/MalformedTitleException.php(49): Message->text()
#15 /var/www/html/w/includes/title/MediaWikiTitleCodec.php(297): MalformedTitleException->__construct('title-invalid-e...', '')
#16 /var/www/html/w/includes/Title.php(3752): MediaWikiTitleCodec->splitTitleString('', 0)
#17 /var/www/html/w/includes/Title.php(377): Title->secureAndSplit()
#18 /var/www/html/w/includes/MediaWiki.php(83): Title::newFromURL('')
#19 /var/www/html/w/includes/MediaWiki.php(140): MediaWiki->parseTitle()
#20 /var/www/html/w/includes/MediaWiki.php(776): MediaWiki->getTitle()
#21 /var/www/html/w/includes/MediaWiki.php(517): MediaWiki->main()
#22 /var/www/html/w/index.php(42): MediaWiki->run()
#23 {main}
```

**Comment by noloader** [comment]
Thanks @Talkless,

I'm bouncing the server now.

Sorry about the delay.

**Comment by Talkless** [comment]
> Sorry about the delay.

Well, StackOverflow still worked so that's OK :-) .

**Comment by noloader** [comment]
@Talkless,

In the future feel free to ping me at *noloader, gmail* account.

It looks like I got the email notification for the bug report and the mailing list message, but I missed it. I get about 2000 to 3000 emails a week and things often fall off my radar that need attention.
